export default {
  ptBr: {
    familyRelations: ['Irmão', 'Mãe', 'Pai', 'Tia', 'Tio', 'Avô',
      'Membro da família'],
    romanticRelations: ['Solteiro', 'Em um relacionamento', 'Casado',
      'Noivo', 'Em uma união estável', 'Morando junto', 'Separado',
      'Divorciado', 'Viúvo',
    ],
    month: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho',
      'Agosto','Setembro','Outubro','Novembro','Dezembro'],
    week: ['Domingo','Segunda-feira','Terça-feira','Quarta-feira',
      'Quinta-feira','Sexta-feira','Sábado'],
  },
  en: {
    familyRelations: ['Bother', 'Son', 'Sister', 'Mother', 'Father', 'Uncle',
      'Aunt', 'Niece', 'Nephew', 'Family Member', 'Daughter', 'Cousin',
      'Grandmother', 'Grandfather', 'Granddaughter', 'Grandson', 'Stepsister',
      'Stepbrother', 'Stepmother', 'Stepfather', 'Stepdaughter', 'Stepson',
      'Sister-in-law', 'Brother-in-law', 'Mother-in-law', 'Father-in-law', 
      'Daughter-in-law', 'Son-in-law', 
    ],
    romanticRelations: ['Single', 'In a relationship', 'Engaged', 'Married',
      'In a civil union', 'In a domestic partnership',
      'In an open relationship', 'It\'s complicated', 'Separated', 
      'Divorced', 'Widowed',
    ],
    month: ['January', 'February', 'March', 'April', 'May', 'June', 'July',
      'August', 'September', 'October', 'November', 'December'],
    week: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
      'Saturday'],
  }
}