export default {
  url: 'https://www.facebook.com/',
  urlGroupMember: id => `https://www.facebook.com/groups/${id}/members/`,
  userForm: '#email',
  passForm: '#pass',
  loginButton: '#loginbutton',
  postSelector: 'div[role=\'region\'] > div[role=\'article\']',
  postFeedSelector: 'div[role=\'feed\'] > div[role=\'article\']',
  argumentSelector: 'arguments[0].click()',
  groupPostDiv: id => `[id*="mall_post_${id}"] > div > div`,
  groupSelectors: {
    postDate: 'abbr',
    groupPostText: 'div._5pbx',
    groupPostBigText: 'span._4a6n',
    groupPostsAuthor: 'span.fwb',
    groupPostImg: 'img.scaledImageFitHeight',
    groupPostLinkImg: 'img.scaledImageFitWidth',
    groupPostLink: 'a._52c6',
    groupAttachedImg: 'div.fbStoryAttachmentImage',
    groupCommentText: 'span[class=\'_3l3x\'] > span',
    groupMoreCommentsButton: 'div[class=\'_4sxd\']',
    groupMemberListName: 'div._60ri',
  },
  profileSelectors: {
    contactInfoIndex: 'div._4qm1 > ul > li > div > div._52ju',
    contactInfoValue: 'div._4qm1 > ul > li > div > div._pt5',
    cityIndex: 'span._2iel',
    cityValue: 'div._4bl9 > div > div > div > div > div.fwn',
    educationIndex: 'div._2lzr',
    educationValue: 'div._173e',
    relashionShip: 'li._3pw9',
    familyRelationShip: 'div#family-relationships-pagelet > div > ul > li',
  }
};